[2025-01-14T03:44:09.800+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-14T03:44:09.822+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_and_update_model.check_and_train manual__2025-01-14T03:33:05.283708+00:00 [queued]>
[2025-01-14T03:44:09.838+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_and_update_model.check_and_train manual__2025-01-14T03:33:05.283708+00:00 [queued]>
[2025-01-14T03:44:09.839+0000] {taskinstance.py:2866} INFO - Starting attempt 4 of 5
[2025-01-14T03:44:09.860+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): check_and_train> on 2025-01-14 03:33:05.283708+00:00
[2025-01-14T03:44:09.871+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=108) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-14T03:44:09.874+0000] {standard_task_runner.py:72} INFO - Started process 110 to run task
[2025-01-14T03:44:09.874+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'train_and_update_model', 'check_and_train', 'manual__2025-01-14T03:33:05.283708+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/craw_check_update.py', '--cfg-path', '/tmp/tmpymdc0rj2']
[2025-01-14T03:44:09.876+0000] {standard_task_runner.py:105} INFO - Job 39: Subtask check_and_train
[2025-01-14T03:44:09.945+0000] {task_command.py:467} INFO - Running <TaskInstance: train_and_update_model.check_and_train manual__2025-01-14T03:33:05.283708+00:00 [running]> on host b954e1e08ba9
[2025-01-14T03:44:10.044+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_and_update_model' AIRFLOW_CTX_TASK_ID='check_and_train' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T03:33:05.283708+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-14T03:33:05.283708+00:00'
[2025-01-14T03:44:10.046+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-14T03:44:10.047+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-14T03:44:10.047+0000] {logging_mixin.py:190} INFO - Current task name:check_and_train state:running start_date:2025-01-14 03:44:09.823724+00:00
[2025-01-14T03:44:10.048+0000] {logging_mixin.py:190} INFO - Dag name:train_and_update_model and current dag run status:running
[2025-01-14T03:44:10.048+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-14T03:44:10.049+0000] {craw_check_update.py:50} INFO - === Bắt đầu quá trình kiểm tra model ===
[2025-01-14T03:44:10.051+0000] {craw_check_update.py:56} INFO - Ngày hiện tại: 2025_01_14, Ngày trước đó: 2025_01_13
[2025-01-14T03:44:10.051+0000] {craw_check_update.py:62} INFO - Đang đọc thông tin từ file: /opt/***/experiment_dir/2025_01_14/results.csv
[2025-01-14T03:44:10.054+0000] {craw_check_update.py:74} ERROR - Lỗi khi đọc file hoặc tính toán mAP50: [Errno 2] No such file or directory: '/opt/***/experiment_dir/2025_01_14/results.csv'
[2025-01-14T03:44:10.054+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-14T03:44:10.065+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-14T03:44:10.066+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=train_and_update_model, task_id=check_and_train, run_id=manual__2025-01-14T03:33:05.283708+00:00, execution_date=20250114T033305, start_date=20250114T034409, end_date=20250114T034410
[2025-01-14T03:44:10.076+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-14T03:44:10.077+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-14T03:44:10.077+0000] {logging_mixin.py:190} INFO - Dag name:train_and_update_model queued_at:2025-01-14 03:44:07.509662+00:00
[2025-01-14T03:44:10.078+0000] {logging_mixin.py:190} INFO - Task hostname:b954e1e08ba9 operator:PythonOperator
[2025-01-14T03:44:10.098+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-14T03:44:10.115+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-14T03:44:10.117+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
